# Force mpv to use integrated graphics via Vulkan device selection 
# Default nvidia gpu
# You can find the device names with: mpv --vulkan-device=help
#vulkan-device='Intel(R) UHD Graphics 620 (KBL GT2)'
#gpu-api=vulkan

really-quiet=yes

msg-level=all=status,cplayer=no,ffmpeg=no,ao=no,demuxer=no

term-playing-msg=----------------------------------------\nNOW PLAYING: ${media-title}\n----------------------------------------

term-status-msg=[${playback-time/full} / ${duration/full}] ${percent-pos}%

